image: php:7.1

cache:
  paths:
  - vendor/

before_script:
  - bash .ci/docker_install.sh > /dev/null

test:
  script:
  - composer testWithStan

after_script:
  - bash <(curl -s https://codecov.io/bash) -f build/logs/clover.xml
